version: "3.7"

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    command: [
      "--lower_case_table_names=1",
      "--ignore-db-dir=lost+found",
      "--character-set-server=utf8",
      "--collation-server=utf8_general_ci",
      "--max_allowed_packet=33554432"]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: oauth_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    restart: always
    volumes:
      - "./database/oauth-db/:/application"
    ports:
      - "3306:3306"
    container_name: oauth-db
    networks:
      - backend-network


volumes:
  oauth-db:

networks:
  backend-network:
    driver: bridge